object UniServerModule: TUniServerModule
  OldCreateOrder = False
  TempFolder = 'temp\'
  Title = 'New Application'
  BGColor = clWhite
  SuppressErrors = []
  Bindings = <>
  CustomCSS.Strings = (
    
      '@import url('#39'https://fonts.googleapis.com/css2?family=Tajawal:wg' +
      'ht@400;500;700&family=Varela+Round&display=swap'#39');'
    ''
    '*{'
    '    padding: 0;'
    '    margin: 0;'
    '    box-sizing: border-box;'
    '}'
    'body{'
    '    background-color: #f3f3f3;'
    '    font-family: "Tajawal", Arial,sans-serif;'
    ''
    '}'
    ''
    '.menu{'
    '    padding: 0;'
    '    display: grid;'
    '    grid-gap: 20px 40px;'
    '}'
    ''
    '.x-big .x-toolbar .x-title {'
    '    font-size: 24px;'
    '    font-weight: bold;'
    '}'
    ''
    '.x-button.x-has-text .x-inner-el {'
    ''
    '    border-radius: 8px;'
    '    background: #000;'
    '    color: #fff;'
    '    padding: 0 32px;'
    '    justify-content: center;'
    '    align-items: center;'
    '    text-align: center;'
    '    cursor: pointer;'
    '    border: 0;'
    ''
    '}        '
    ''
    'x-input-el{'
    '    text-transform: uppercase;'
    '    background-color: #FFF !important;'
    '    '
    '}'
    ''
    '.x-center {'
    '  background: #000;'
    '  color: #FFF;'
    '  '
    '}                  '
    ''
    '.x-panel-outer-border-trbl {'
    '    border-color: #FFF !important;'
    '    border-width: 1px !important;'
    '}'
    ''
    ''
    '       '
    '.heading{'
    '    background-color: #000;'
    '    color: #ffffff;'
    '    margin-bottom: 30px;'
    '    padding: 20px 0 30px 0;'
    '    grid-column: 1/-1;'
    '    text-align: center;'
    '}'
    '.heading>h1{'
    '    font-weight: 400;'
    '    font-size: 1.2rem;'
    '    letter-spacing: 0.70rem;'
    '    margin-bottom: 10px;'
    '}'
    '.heading>h3{'
    '    font-weight: 600;'
    '    font-size: 1rem;'
    '    letter-spacing: 0.90rem;'
    '}'
    ''
    '.heading>h2{'
    '    font-size: 1.4rem;'
    '}'
    ''
    ''
    '.details-total{'
    ' padding: 2px 20px 0px 20px;'
    ''
    '}'
    ''
    '.details-total>h4{'
    '   font-size: 1rem;'
    ' '
    '}'
    ''
    '.details-total>p{'
    '   font-size: 1rem;'
    '   color: #6f6f6f;'
    '   letter-spacing: 0.10rem;'
    '}'
    ''
    '')
  SSL.SSLOptions.RootCertFile = 'root.pem'
  SSL.SSLOptions.CertFile = 'cert.pem'
  SSL.SSLOptions.KeyFile = 'key.pem'
  SSL.SSLOptions.Method = sslvTLSv1_1
  SSL.SSLOptions.SSLVersions = [sslvTLSv1_1]
  SSL.SSLOptions.Mode = sslmUnassigned
  SSL.SSLOptions.VerifyMode = []
  SSL.SSLOptions.VerifyDepth = 0
  ConnectionFailureRecovery.ErrorMessage = 'Connection Error'
  ConnectionFailureRecovery.RetryMessage = 'Retrying...'
  Height = 208
  Width = 401
end
